### ISSUE TITLE
place_order() returns HTTP Error

### ISSUE THREAD

**Issue by alahiri-quora** [Jamonek/Robinhood#28]
buy/sell order returns something like:
HTTPError: 400 Client Error: Bad Request for url:

**Comment by Tapas-Joshi** [comment]
I am having the same problem. Did you find any solution?

**Comment by akshayshetty** [comment]
Getting the same error.

**Comment by Jamonek** [comment]
I'm looking into it

**Comment by Tapas-Joshi** [comment]
Thank you. It would be great if you can give us the solution.

**Comment by shomran** [comment]
I have same problem.  Thank you Jamone!

**Comment by myanmccann** [comment]
Same issue,

```
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url:
```

 I'd love to figure out a solution, thanks Jamone!!

**Comment by myanmccann** [comment]
@Jamonek I think it's either a user-agent issue, or a requests vs. urllib issue. I don't know if this helps, but I really want to get this working!

**Comment by shomran** [comment]
when I get res.json() , I end up with:
{'side': ['This field is required.'], 'quantity': ['This field is required.'], 'time_in_force': ['This field is required.'], 'account': ['This field is required.'], 'symbol': ['This field is required.'], 'instrument': ['This field is required.'], 'type': ['This field is required.'], 'trigger': ['This field is required.']}

It seems that post command doesn't transfer the payload!

**Comment by myanmccann** [comment]
@shomran @Jamonek @Tapas-Joshi @alahiri-quora @akshayshetty I figured it out!!!!! I saw that the login post was made with 'data' as the argument rather than 'params'...so I changed the order post argument name to 'data' rather than params, and the post request seemed to accept it rather than 'params' on line 723/near it.

**Comment by Tapas-Joshi** [comment]
Thanks a lot @myanmccann 
Worked like a charm. 
Appreciate it man

**Comment by lf3zumba** [comment]
Thank you @myanmccann, that worked!

**Comment by CamDHall** [comment]
I'm confused as to what I need to change to get this to work. I still get the error.

**Comment by Jamonek** [comment]
@CamDHall It has been fixed by @bdowling. #42

**Comment by rupeshshyam** [comment]
Still fails when I have low cash balance than buy order value.

    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/orders/

**Comment by tedchou12** [comment]
Thanks for the API. I saw that `time_in_force` is required for order, but 
```time_in_force = str(time_in_force).lower()``` will make the `None` to `none` efficiently not valid, so what must be done is to place this before the ```time_in_force = str(time_in_force).lower()```:
```        if(time_in_force is None):
            raise(ValueError('Time in Force is required call to submit_order'))```
Efficiently ```def submit_order(self,
                     instrument_URL=None,
                     symbol=None,
                     order_type=None,
                     time_in_force=None,
                     trigger=None,
                     price=None,
                     stop_price=None,
                     quantity=None,
                     side=None):
        """Submits order to Robinhood

            Notes:
                This is normally not called directly.  Most programs should use
                one of the following instead:

                    place_market_buy_order()
                    place_limit_buy_order()
                    place_stop_loss_buy_order()
                    place_stop_limit_buy_order()
                    place_market_sell_order()
                    place_limit_sell_order()
                    place_stop_loss_sell_order()
                    place_stop_limit_sell_order()

            Args:
                instrument_URL (str): the RH URL for the instrument
                symbol (str): the ticker symbol for the instrument
                order_type (str): 'MARKET' or 'LIMIT'
                time_in_force (:enum:`TIME_IN_FORCE`): GFD or GTC (day or
                                                       until cancelled)
                trigger (str): IMMEDIATE or STOP enum
                price (float): The share price you'll accept
                stop_price (float): The price at which the order becomes a
                                    market or limit order
                quantity (int): The number of shares to buy/sell
                side (str): BUY or sell

            Returns:
                (:obj:`requests.request`): result from `orders` put command
        """

        # Start with some parameter checks. I'm paranoid about $.
        if(instrument_URL is None):
            if(symbol is None):
                raise(ValueError('Neither instrument_URL nor symbol were passed to submit_order'))
            instrument_URL = self.instruments(symbol)[0]['url']

        if(symbol is None):
            symbol = self.session.get(instrument_URL, timeout=15).json()['symbol']

        if(side is None):
            raise(ValueError('Order is neither buy nor sell in call to submit_order'))

        if(order_type is None):
            if(price is None):
                if(stop_price is None):
                    order_type = 'market'
                else:
                    order_type = 'limit'

        if(time_in_force is None):
            raise(ValueError('Time in Force is required call to submit_order'))

        symbol = str(symbol).upper()
        order_type = str(order_type).lower()
        time_in_force = str(time_in_force).lower()
        trigger = str(trigger).lower()
        side = str(side).lower()

        if(order_type != 'market') and (order_type != 'limit'):
            raise(ValueError('Invalid order_type in call to submit_order'))

        if(order_type == 'limit'):
            if(price is None):
                raise(ValueError('Limit order has no price in call to submit_order'))
            if(price <= 0):
                raise(ValueError('Price must be positive number in call to submit_order'))

        if(trigger == 'stop'):
            if(stop_price is None):
                raise(ValueError('Stop order has no stop_price in call to submit_order'))
            if(price <= 0):
                raise(ValueError('Stop_price must be positive number in call to submit_order'))

        if(stop_price is not None):
            if(trigger != 'stop'):
                raise(ValueError('Stop price set for non-stop order in call to submit_order'))

        if(price is None):
            if(order_type == 'limit'):
                raise(ValueError('Limit order has no price in call to submit_order'))

        if(price is not None):
            if(order_type.lower() == 'market'):
                raise(ValueError('Market order has price limit in call to submit_order'))

        price = float(price)

        if(quantity is None):
            raise(ValueError('No quantity specified in call to submit_order'))

        quantity = int(quantity)

        if(quantity <= 0):
            raise(ValueError('Quantity must be positive number in call to submit_order'))

        payload = {}

        for field, value in [
                                ('account', self.get_account()['url']),
                                ('instrument', instrument_URL),
                                ('symbol', symbol),
                                ('type', order_type),
                                ('time_in_force', time_in_force),
                                ('trigger', trigger),
                                ('price', price),
                                ('stop_price', stop_price),
                                ('quantity', quantity),
                                ('side', side)
                            ]:
            if(value is not None):
                payload[field] = value

        res = self.session.post(endpoints.orders(), data=payload, timeout=15)
        res.raise_for_status()

        return res```.
This is a bug~?
